[openstack]
node1 ansible_host=192.168.0.200
node2 ansible_host=192.168.0.201
node3 ansible_host=192.168.0.202

[openstack:vars]
ansible_user=openstack
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
